/**
 * Regex-based `.nuspec` metadata parser (see #86) — deliberately not a DOM
 * parser, for consistency with the rest of this extension's nuget.config
 * XML handling (#85), which stays regex/string-based because it also has to
 * write surgical edits back to disk. A `.nuspec` is read-only here, but
 * using the same approach keeps one way of doing XML text extraction in the
 * codebase instead of two, and lets this reuse `maskXmlComments` directly.
 *
 * Nuspec files are machine-generated by `nuget pack`/`dotnet pack` and
 * rarely hand-edited, so the comment-swallowing class of bug from #85 is
 * lower-risk here — but a privately-authored package's hand-crafted nuspec
 * with an explanatory `<!-- -->` comment isn't impossible, so every regex
 * below still matches against a comment-masked copy: boundaries are found
 * on the masked text (via the `d`/hasIndices flag for exact offsets), then
 * sliced out of the real, unmasked text.
 */

import { maskXmlComments } from './xmlComments';
import type { PackageLicense, PackageRepository } from './types';

export interface NuspecMetadata {
  id: string;
  version: string;
  authors: string;
  owners?: string;
  projectUrl?: string;
  licenseUrl?: string;
  license?: PackageLicense;
  copyright?: string;
  repository?: PackageRepository;
  description: string;
  tags: string[];
}

/** Real (unmasked) text between `<tagName ...>` and `</tagName>`, or undefined if absent. */
function extractSection(xml: string, tagName: string): string | undefined {
  const masked = maskXmlComments(xml);
  const re = new RegExp(`<${tagName}\\b[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'id');
  const m = re.exec(masked) as (RegExpExecArray & { indices: RegExpIndicesArray }) | null;
  const bounds = m?.indices[1];
  if (!bounds) return undefined;
  return xml.slice(bounds[0], bounds[1]);
}

/**
 * Plain text between `<tag>` and `</tag>` for a simple leaf element, with
 * the two forms NuGet accepts: literal text, or a `<![CDATA[...]]>` wrapper
 * (common for a `<description>` containing characters that would otherwise
 * need escaping — angle brackets, ampersands in prose, embedded markdown).
 * A plain text-between-tags extraction would otherwise leak the literal
 * `<![CDATA[`/`]]>` markers into the displayed value.
 */
function extractLeafText(xml: string, tagName: string): string | undefined {
  const inner = extractSection(xml, tagName);
  if (inner === undefined) return undefined;
  const trimmed = inner.trim();
  const cdata = /^<!\[CDATA\[([\s\S]*?)\]\]>$/.exec(trimmed);
  return unescapeXmlEntities((cdata ? cdata[1] : trimmed).trim());
}

function unescapeXmlEntities(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

function extractAttr(tagOpen: string, attrName: string): string | undefined {
  const re = new RegExp(`\\b${attrName}\\s*=\\s*(?:"([^"]*)"|'([^']*)')`, 'i');
  const m = re.exec(tagOpen);
  if (!m) return undefined;
  return unescapeXmlEntities(m[1] ?? m[2] ?? '');
}

/** `<license type="expression">MIT</license>` or `<license type="file">LICENSE.txt</license>`. */
function parseLicense(metadata: string): PackageLicense | undefined {
  const masked = maskXmlComments(metadata);
  const openMatch = /<license\b([^>]*)>/i.exec(masked);
  if (!openMatch) return undefined;
  const type = extractAttr(openMatch[1], 'type');
  if (type !== 'expression' && type !== 'file') return undefined;
  const value = extractLeafText(metadata, 'license');
  if (!value) return undefined;
  return { type, value };
}

/** `<repository type="git" url="..." commit="..." />` — a self-closing `<add>`-shaped tag, no body. */
function parseRepository(metadata: string): PackageRepository | undefined {
  const masked = maskXmlComments(metadata);
  const m = /<repository\b([^>]*)\/?>/i.exec(masked);
  if (!m) return undefined;
  const url = extractAttr(m[1], 'url');
  if (!url) return undefined;
  const commit = extractAttr(m[1], 'commit');
  return commit ? { url, commit } : { url };
}

/** `authors`/`owners`: comma-separated within one element. `tags`: space-separated within one element — different delimiters for two similar-looking fields. */
function splitCommaList(value: string): string {
  return value.split(',').map((v) => v.trim()).filter(Boolean).join(', ');
}

function splitTags(value: string): string[] {
  return value.split(/\s+/).map((v) => v.trim()).filter(Boolean);
}

export function parseNuspec(xml: string): NuspecMetadata | undefined {
  const metadata = extractSection(xml, 'metadata');
  if (metadata === undefined) return undefined;

  const id = extractLeafText(metadata, 'id');
  const version = extractLeafText(metadata, 'version');
  if (!id || !version) return undefined;

  const authorsRaw = extractLeafText(metadata, 'authors') ?? '';
  const ownersRaw = extractLeafText(metadata, 'owners');
  const tagsRaw = extractLeafText(metadata, 'tags');

  return {
    id,
    version,
    authors: splitCommaList(authorsRaw),
    owners: ownersRaw ? splitCommaList(ownersRaw) : undefined,
    projectUrl: extractLeafText(metadata, 'projectUrl'),
    licenseUrl: extractLeafText(metadata, 'licenseUrl'),
    license: parseLicense(metadata),
    copyright: extractLeafText(metadata, 'copyright'),
    repository: parseRepository(metadata),
    description: extractLeafText(metadata, 'description') ?? '',
    tags: tagsRaw ? splitTags(tagsRaw) : [],
  };
}
